name: Send Daily Islamic Quote

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8:00 AM UTC every day
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Send Daily Islamic Quote
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python send_quote.py
